[[main]]
  identifier = "GoNote"
  name = "Go"
  url = "tech/GoNote"
  weight = 1

[[main]]
  identifier = "TSDB"
  name = "TSDB"
  url = "component/TimeSeries"
  weight = 2

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 3
